[package]
name = "markdown-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.35"
config = "0.14.0"
indexmap = "2.2.6"
itertools = "0.10.5"
nanoid = "0.4.0"
nucleo-matcher = "0.3.1"
once_cell = "1.18.0"
pathdiff = "0.2.1"
rayon = "1.7.0"
regex = "1.10.2"
ropey = "1.6.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
shellexpand = "3.1.0"
tokio = { version = "1.34.0", features = ["full"] }
tower-lsp = { git = "https://github.com/Feel-ix-343/tower-lsp" }
walkdir = "2.4.0"
